mysite/arduinoapp/urls.py
from django.urls import include
from django.urls import path
from .views import (InfoIndexView,
                    InfoIndexRCS,
                    StationCreateView,
                    StationListView,
                    ArduinoCreateView,
                    ArduinoListView,
                    StationViewSet,
                    usb_web,
                    InfoSettingsView,
                    InfoAboutRCS4,
                    Saratov_1RCS4,
                    )
from rest_framework.routers import DefaultRouter
from django.conf.urls.static import static
from django.conf import settings
app_name = 'arduinoapp'

routers = DefaultRouter()
routers.register("station", StationViewSet)
urlpatterns = [
    path('', InfoIndexView.as_view(), name='info-index'),
    path("rcs/", InfoIndexRCS.as_view(), name = "rcs-index"),
    path("settings/", InfoSettingsView.as_view(), name="info-settings"),
    path("about/", InfoAboutRCS4.as_view(), name="info-aboutRCS4"),
    path("saratov_1/", Saratov_1RCS4.as_view(), name="info-Saratov_1RCS4"),
    path("api/", include(routers.urls)),
    path("station/", StationListView.as_view(), name="info-list"),
    path("station/create", StationCreateView.as_view(), name="info-create"),
    path("arduino/create", ArduinoCreateView.as_view(), name="arduino-create"),
    path("arduino/list", ArduinoListView.as_view(), name="arduino-list"),
    path("arduino/info",usb_web, name="info-arduino"),
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import AboutView, RegisterView, UpdateUserProfile, logout_view, AdditionalInformation

app_name = 'myauth'


urlpatterns = [
    path("login/",
          LoginView.as_view(
              template_name="myauth/login.html",
              redirect_authenticated_user=True), name="login"),
    path('logout/', logout_view, name='logout'),
    path('about/', AboutView.as_view(), name='about-me'),
    path('additional-info/', AdditionalInformation.as_view(), name='additional_information'),
    path('register/', RegisterView.as_view(), name='register'),
    path('users/<pk>update-profile', UpdateUserProfile.as_view(), name='user-profile-update'),

]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', include('arduinoapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('rcs_1/', include("rcs_1.urls")),
    path('rcs_2/', include("rcs_2.urls")),
    path("req/", include("requestdataapp.urls")),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path("api/", include("myapiapp.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/rcs_1/urls.py
from django.urls import include
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import InfoIndexView, StationListView, ArduinoCreateView, ArduinoListView, usb_web, StationCreateView, MicrocomputerListView, MicrocomputerCreateView
app_name = 'rcs_1'

routers = DefaultRouter()

urlpatterns = [
    path('', InfoIndexView.as_view(), name='info-index'),
    path("station/", StationListView.as_view(), name="info-list"),
    path("station/create/", StationCreateView.as_view(), name="info-create"),
    path("arduino/create/", ArduinoCreateView.as_view(), name="arduino-create"),
    path("arduino/list/", ArduinoListView.as_view(), name="arduino-list"),
    path("arduino/info/", usb_web, name="info-arduino"),
    path("micro/create/", MicrocomputerCreateView.as_view(), name="micro-create"),
    path("micro/list/", MicrocomputerListView.as_view(), name="micro-list"),
]

mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


def info_arduino_directory_path(instance: "Profile", filename: str) -> str:
    return "profiles/profile_{user}/documents/{filename}".format(
        user=instance.user.pk,
        filename=filename,
    )
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100, null=True)
    position = models.CharField(max_length=100)
    document = models.FileField(null=True, blank=True, upload_to=info_arduino_directory_path)
class Email(models.Model):
    email = models.EmailField(max_length=100)

mysite/myauth/forms.py
from django import forms
from myauth.models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class ProfileForm(forms.ModelForm):
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    class Meta:
        models = Profile
        fields = "username", "last_name", "password1", "password2"
    document = forms.FileField(
        widget=forms.ClearableFileInput(),
    )

mysite/myauth/views.py
from django.http import request
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView
from .forms import ProfileForm
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from .models import Profile
from django.contrib.auth.views import LogoutView
# Create your views here.

class AboutView(ListView):
    """
    Информация о пользователе
    """
    template_name = "myauth/about-me.html"
    form_class = ProfileForm
    queryset = Profile.objects.all()


class AdditionalInformation(ListView):
    """
    Дополнительная информация о пользователе
    """
    model = Profile
    template_name = "myauth/additional_information.html"
    context_object = "profiles"
    queryset = Profile.objects.all()
class RegisterView(CreateView):
    """
    Регистрация пользователя
    """
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy('myauth:about-me')

    def form_valid(self, form):
        """
        Проверка на валидность регистрации
        :param form:
        :return:
        """
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")

        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class UpdateUserProfile(UpdateView):
    """
    Обновление профиля пользователя
    """
    model = Profile
    fields = "user","name","position", "document"
    template_name = "myauth/user-profile-update.html"
    #success_url = reverse_lazy('myauth:about-me')



def logout_view(request):
    """
    Выход с сайта
    :param request:
    :return:
    """
    logout(request)
    return redirect('myauth:login')

mysite/myauth/templates/myauth/about-me.html
{% extends "myauth/base.html" %}
{% block body %}
<h1>Информация о пользователе</h1>
<div style="position: absolute; top: 10px; right: 10px;">
    Добро пожаловать, {{ user.username }}
</div>
<div>
{% if user.is_authenticated%}
    <h2>Детали</h2>
    <p>Имя короткое:{{ user.username }}</p>
    <p>Имя:{{user.first_name}}</p>
    <p>Отчество:{{ user.last_name }}</p>
</div>

    {% else %}
    <h2>User is anonymous</h2>
{% endif %}
{% if user.is_staff %}
    <p>Staff-user:{{ user.username }}</p>
    {% else %}
        <h2>User is not staff</h2>
{% endif %}

    <div>
    {% if profiles %}
    {% for profile in profiles %}
        <p> Должность:{{ profile.position }}</p>
        {% endfor %}
    </div>
        {% else %}
            <h3>Нет информации о должности</h3>
        {% endif %}
    <div>
        <a href="{% url 'arduinoapp:rcs-index' %}">Возвращение на главную страницу</a>
    </div>
    <div>
        <a href="{% url 'myauth:logout' %}">Выйти</a>
    </div>

    <div>
        <a href="{% url 'myauth:user-profile-update' user.pk %}"> Обновить профиль</a>
    </div>
{% endblock  %}

mysite/myauth/templates/myauth/additional_information.html
{% extends "myauth/base.html" %}>

{% block title %}
    additional information
{% endblock %}

{% block body %}
<h1>Дополнительная информация о пользователе</h1>
<div>
    {% if object_list%}
    {% for profile in object_list %}
    <p>Имя:{{ profile.name}}</p>
    <p>Рабочая позиция:{{ profile.position }}</p>
    {% endfor %}
    {% else %}
    <h3>Нет существующих пользователей</h3>
    {% endif %}
</div>


{% endblock %}

mysite/myauth/templates/myauth/base.html
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
    <style>
        body {
            background-color: gray;
        }
    </style>
</head>
<body>
{% block body %}
Base Body
{% endblock %}

<div>
</div>
<div>
</div>
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends "myauth/base.html" %}


{% block title %}
    Login
{% endblock  %}

{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" style="background-color:white; border-radius:5px">Войти</button>
</form>
    <div>
        <a href="{% url 'arduinoapp:rcs-index' %}"><button style="background-color:white; border-radius:5px">Назад</button></a>
    </div>
{% endblock  %}

mysite/myauth/templates/myauth/register.html
{% extends "myauth/base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Регистрация
{% endblock  %}


{% block body %}
    <h1>Регистрация</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Регистрация" style="background-color:white; border-radius:5px">
    </form>
    <div>
        <a href="{% url 'arduinoapp:rcs-index' %}"><button style="background-color:white; border-radius:5px">Назад</button></a>
        <a href="{% url 'myauth:login' %}"><button style="background-color:white; border-radius:5px">У меня уже есть аккаунт</button></a>
    </div>

{% endblock  %}

mysite/myauth/templates/myauth/user-profile-update.html
{% extends "myauth/base.html" %}

{% block title %}
    Update Profile
{% endblock %}

{% block body %}
<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Ообновить профиль" style="background-color:white; border-radius:5px">
</form>
{% endblock %}