mysite/arduinoapp/urls.py
from django.urls import include
from django.urls import path
from .views import (InfoIndexView,
                    InfoIndexRCS,
                    StationCreateView,
                    StationListView,
                    ArduinoCreateView,
                    ArduinoListView,
                    StationViewSet,
                    usb_web,
                    InfoSettingsView,
                    InfoAboutRCS4,
                    Saratov_1RCS4,
                    )
from rest_framework.routers import DefaultRouter
from django.conf.urls.static import static
from django.conf import settings
app_name = 'arduinoapp'

routers = DefaultRouter()
routers.register("station", StationViewSet)
urlpatterns = [
    path('', InfoIndexView.as_view(), name='info-index'),
    path("rcs/", InfoIndexRCS.as_view(), name = "rcs-index"),
    path("settings/", InfoSettingsView.as_view(), name="info-settings"),
    path("about/", InfoAboutRCS4.as_view(), name="info-aboutRCS4"),
    path("saratov_1/", Saratov_1RCS4.as_view(), name="info-Saratov_1RCS4"),
    path("api/", include(routers.urls)),
    path("station/", StationListView.as_view(), name="info-list"),
    path("station/create", StationCreateView.as_view(), name="info-create"),
    path("arduino/create", ArduinoCreateView.as_view(), name="arduino-create"),
    path("arduino/list", ArduinoListView.as_view(), name="arduino-list"),
    path("arduino/info",usb_web, name="info-arduino"),
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import AboutView, RegisterView, UpdateUserProfile, logout_view, AdditionalInformation

app_name = 'myauth'


urlpatterns = [
    path("login/",
          LoginView.as_view(
              template_name="myauth/login.html",
              redirect_authenticated_user=True), name="login"),
    path('logout/', logout_view, name='logout'),
    path('about/', AboutView.as_view(), name='about-me'),
    path('additional-info/', AdditionalInformation.as_view(), name='additional_information'),
    path('register/', RegisterView.as_view(), name='register'),
    path('users/<pk>update-profile', UpdateUserProfile.as_view(), name='user-profile-update'),

]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', include('arduinoapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('rcs_1/', include("rcs_1.urls")),
    path('rcs_2/', include("rcs_2.urls")),
    path("req/", include("requestdataapp.urls")),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path("api/", include("myapiapp.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/rcs_1/urls.py
from django.urls import include
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import InfoIndexView, StationListView, ArduinoCreateView, ArduinoListView, usb_web, StationCreateView, MicrocomputerListView, MicrocomputerCreateView
app_name = 'rcs_1'

routers = DefaultRouter()

urlpatterns = [
    path('', InfoIndexView.as_view(), name='info-index'),
    path("station/", StationListView.as_view(), name="info-list"),
    path("station/create/", StationCreateView.as_view(), name="info-create"),
    path("arduino/create/", ArduinoCreateView.as_view(), name="arduino-create"),
    path("arduino/list/", ArduinoListView.as_view(), name="arduino-list"),
    path("arduino/info/", usb_web, name="info-arduino"),
    path("micro/create/", MicrocomputerCreateView.as_view(), name="micro-create"),
    path("micro/list/", MicrocomputerListView.as_view(), name="micro-list"),
]

mysite/rcs_2/urls.py
from django.urls import include
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import InfoIndexView, StationListView, ArduinoCreateView, ArduinoListView, usb_web, StationCreateView, MicrocomputerListView, MicrocomputerCreateView
app_name = 'rcs_2'

routers = DefaultRouter()

urlpatterns = [
    path('', InfoIndexView.as_view(), name='info-index'),
    path("station/", StationListView.as_view(), name="info-list"),
    path("station/create/", StationCreateView.as_view(), name="info-create"),
    path("arduino/create/", ArduinoCreateView.as_view(), name="arduino-create"),
    path("arduino/list/", ArduinoListView.as_view(), name="arduino-list"),
    path("arduino/info/", usb_web, name="info-arduino"),
    path("micro/create/", MicrocomputerCreateView.as_view(), name="micro-create"),
    path("micro/list/", MicrocomputerListView.as_view(), name="micro-list"),
]

mysite/arduinoapp/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

def product_document_directory_path(instance: "Station", filename: str) -> str:
    return "station/station_{pk}/documents/{filename}".format(
        pk=instance,
        filename=filename,
    )
class Station(models.Model):
    """
    Модель Station представялет иноформацию
    о станции и анализировать эти данные
    """
    objects = None
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    temperature_info = models.IntegerField(default=0)
    data_created = models.DateTimeField(default=timezone.now)
    documents = models.FileField(null=True, blank=True, upload_to=product_document_directory_path)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Station'
        
class Arduino(models.Model):
    """
    Модель Arduino предоставляет информацию о состоянии 
    темперартуры на станции
    """
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    station  = models.ForeignKey(Station, on_delete=models.CASCADE)
    temperature_info  = models.IntegerField(default=0)
    update_data = models.DateTimeField(default=timezone.now)
    
    class Meta:
        verbose_name = 'Arduino'

class Sensor_Data(models.Model):
    """"
    Модель Sensor_Data предоставляет
    информацию о температуре на станции
    """
    name = models.CharField(max_length=200)
    temperature_info = models.IntegerField(default=0)


class Image(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.title

class Microcomputer(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    temperature_info = models.IntegerField(default=0)
    update_data = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Microcomputer'

mysite/arduinoapp/forms.py
from django import forms
from .models import Station, Arduino, Image

class StationForm(forms.ModelForm):
    class Meta:
        model = Station
        fields = "name", "temperature_info"
        
class ArduinoForm(forms.ModelForm):
    class Meta:
        model = Arduino
        fields = "name", "temperature_info", "station"


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'image')

mysite/arduinoapp/views.py
import calendar
import csv
import datetime
from argparse import Action
import logging
from csv import DictWriter
from io import TextIOWrapper
from re import split
from time import timezone
from timeit import default_timer
from urllib.request import Request
from requests import Response
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from django.contrib.admin import action
from django.http import HttpRequest, HttpResponse, JsonResponse, response
from django.http.multipartparser import MultiPartParser
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, TemplateView
from rest_framework.utils import json
from rest_framework.viewsets import ModelViewSet
from twisted.protocols.sip import Response
from .common import save_csv_stations
from .forms import StationForm
from .models import Station, Arduino, Sensor_Data, Image
import serial
from .serializer import StationSerializer
import requests
from drf_spectacular.utils import extend_schema, OpenApiResponse
from rest_framework.decorators import action
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail
# Create your views here.


log = logging.getLogger(__name__)
@extend_schema(description="Station views CRUD")
class StationViewSet(ModelViewSet):
    """"
    Набор представлений для действий над Station
    Полный CRUD для операций над станциями
    """
    queryset = Station.objects.all()
    serializer_class = StationSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]

    filterset_fields = [
        "name",
        "temperature_info",
        "data_created",
    ]
    @extend_schema(
        summary="Get one station ID",
        description="Retrieves **station**, returns 404 if not found",
        responses={
            200: StationSerializer,
            404: OpenApiResponse(description="Empty response, station by id not found")
        }
    )
#    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type='text/csv')
        filename = "info-station.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "temperature_info",
            "data_created",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for station in queryset:
            writer.writerow({
                field: getattr(station, field)
                for field in fields
            })
            return response
#    @action(
        detail=False,
        methods = ["post"],
        parser_classes=[MultiPartParser]
#    )
    def upload_csv(self, request: Request):
        stations = save_csv_stations(
            request.FILES["file"],
            encoding=request.encoding,
        )
        serializer = self.get_serializer(stations, many=True)
        return Response(serializer.data)


class InfoIndexRCS(View):
    """
    Страница трех РЦС
    """
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(request, "arduinoapp/rcs-index.html")

    def calendar_view(request):
        cal = calendar.monthcalendar(year=2024, month=10)
        context = {
            'calendar': cal,
        }
        return render(request, "arduinoapp/rcs-index.html", context=context)


class InfoSettingsView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(request, "arduinoapp/info-settings.html")

class InfoAboutRCS4(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(request, "arduinoapp/info-aboutRCS4.html")

class Saratov_1RCS4(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(request, "arduinoapp/info-Saratov_1RCS4.html")

from .forms import ImageForm

class HomePageView(ListView):
    model = Image
    template_name = 'rcs-index.html'

class InfoIndexView(View):
    """
    Главная страница сайта
    """
    def get(self, request: HttpRequest) -> HttpResponse:
        stations = [
            ('Новая НС', 28),
            ('Аткарск', 30),
            ('Саратов-1', 28),
        ]
        context = {
            "time_running": default_timer(),
            'station': stations,
        }
        log.debug("Станции их индексы: %s", stations)
        log.info("Станции")
        print("Станции", context)
        return render(request, "arduinoapp/info-index.html", context=context)



class StationListView(ListView):
    """
    Список станций и какая-то информация о ней
    """
    template_name = "arduinoapp/info-list.html"
    context_object_name = "station"
    queryset = Station.objects.all()


def station_create(self, request: HttpRequest) -> HttpResponse:
    """
    POST запрос на создание станции
    :param self:
    :param request:
    :return:
    """
    if request.method == 'POST':
        form = StationForm(request.POST)
        if form.is_valid():
            form.save()
            url = reverse("arduinoapp/info-list.html")
            return redirect(url)
    else:
        form = StationForm()
    context = {
        "form": form,
    }
    return render(request, "arduinoapp/info-create.html", context=context)


class StationCreateView(CreateView):
    """
    Создание станции и какая-то информация о ней
    """
    model = Station
    fields = "name", "temperature_info", "documents",
    template_name = 'arduinoapp/info-create.html'
    success_url = reverse_lazy("arduinoapp:info-create")
    
    
class ArduinoCreateView(CreateView):
    """
    Создание Arduino и какая-то информация о ней
    """
    model = Arduino
    fields = "name", "temperature_info", "station"
    template_name = 'arduinoapp/arduino-create.html'
    success_url = reverse_lazy("arduinoapp:arduino-create")
    
    
class ArduinoListView(ListView):
    """
    Список Arduino
    """
    template_name = "arduinoapp/arduino-list.html"
    context_object_name = "arduinos"
    queryset = Arduino.objects.all()


def usb_web(request: HttpRequest) -> HttpResponse:
    """
    Информация с Arduino
    """
    with open("arduino.csv", "r", encoding="utf-8") as file:
        for line in file.read().split("\n"): # Про тестить maxsplit, что бы произвести разделение на несколько строк
            name = line.strip().split(",")
            Sensor_Data.objects.create(name=name)
            data_sensor = [
                ("", line)
            ]
            context = {
                "data_sensor": data_sensor,
            }
            return render(request, "arduinoapp/info-arduino.html", context=context)

class DataSensorListView(ListView):
    """
    Информация с Arduino для анализа
    и работы с этими данными
    """
    template_name = "arduinoapp/arduino-list.html"
    context_object_name = "Sensor_datas"
    queryset = Sensor_Data.objects.all()

mysite/arduinoapp/templates/arduinoapp/arduino-create.html
{% extends "arduinoapp/base.html" %}

{% block title %}
    Create Arduino
{% endblock  %}

{% block body %}
    <h1>Добавление данных с ардуино</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" style="background-color:white; border-radius:5px">
                Создание
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'arduinoapp:info-list' %}"><button style="background-color:white; border-radius:5px">Возвращение на страницу с перечнем станций и ардуино</button></a>
    </div>
    <div>
        <a href="{% url 'arduinoapp:info-index' %}"><button style="background-color:white; border-radius:5px">Возвращение на главную страницу</button></a>
    </div>
{% endblock  %}

mysite/arduinoapp/templates/arduinoapp/arduino-list.html
{% extends "arduinoapp/base.html" %}

{% block title %}
    Info list
{% endblock  %}

{% block body %}
<h1>Информация о станции Саратов-1</h1>
<div>
    <ul>
        {% for name, temperature_info in data_sensor %}
        <li> {{name|linenumbers}} {{temperature_info}} </li>
    </ul>
    {% endfor %}
</div>

{% endblock  %}

mysite/arduinoapp/templates/arduinoapp/base.html
<!DOCTYPE html>
<html lang="ru">
{% load i18n %}
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
    <style>
        body {
            background-color: gray;
        }
    </style>
</head>
<body>
{% block body %}
Base Body
{% endblock %}
<div>
    Время: {% now 'H:i'%}
</div>
<div>
    {% now 'l' as current_weekday%}
    Сегодня: {{current_weekday}}
</div>
{% block content %}
{% endblock %}
</body>
</html>

mysite/arduinoapp/templates/arduinoapp/data-arduino.html
<html>
<head>
<title>Освещённость датчика света</title>
<meta http-equiv="Refresh" content="15" />
</head>
<body>
<h2>Освещённость датчика: {{ line }}!</h2>
    <ul>
        {% for name, temperature_info in  %}
        <li>{{name|linenumbers}} ({{name|length}}) {{temperature_info}}</li>
    </ul>
<p align="center">Данные обновляются каждые 15 сек!</p>
</body>
</html>

mysite/arduinoapp/templates/arduinoapp/info-Saratov_1RCS4.html
{% extends "arduinoapp/base.html" %}

{% block title %}
Саратов-1
{% endblock %}

{% block body %}
<h1>Станция Саратов-1</h1>

<div>
    <a href="{% url 'arduinoapp:info-arduino' %}"><button style="background-color:white; border-radius:5px">Управление</button></a>
</div>
<div>
    <a href="{% url 'arduinoapp:arduino-list' %}"><button style="background-color:white; border-radius:5px">Информация</button></a>
</div>
<div>
    <a href="{% url 'arduinoapp:info-index' %}"><button style="background-color:white; border-radius:5px">Назад</button></a>
</div>
{% endblock%}

mysite/arduinoapp/templates/arduinoapp/info-aboutRCS4.html
{% extends "arduinoapp/base.html" %}


{% block title %}
Информация о станции Саратов-1
{% endblock %}


{% block body %}
<div>
    <a href="{% url 'arduinoapp:arduino-list' %}"><button style="background-color:white; border-radius:5px">Информация о станции Саратов-1</button></a>
</div>
{% endblock %}

mysite/arduinoapp/templates/arduinoapp/info-arduino.html
{% extends "arduinoapp/base.html" %}

{% block title %}
    Управление Ардуино
{% endblock  %}

{% block body %}
<meta charset="UTF-8">
<!--<meta http-equiv="Refresh" content="15" />-->
<div>
    <h1>Управление Ардуино</h1>
</div>
<div class="estimated-price">
    <label>Данные с Ардуино:</label>
</div>
<div>
    <ul>
        {% for name, temperature_info in data_sensor %}
        <li> {{name|linenumbers}} {{temperature_info}} </li>
    </ul>
    {% endfor %}
</div>
<div>
    IP адрес Ардуино на станции Новая НС:
    <a href="http://192.168.0.102">192.168.0.102</a>
</div>
<div>
    <a href="{% url 'arduinoapp:info-index' %}"><button style="background-color:white; border-radius:5px">Возвращение на главную страницу</button></a>
</div>
<div>
    <a href="{% url 'arduinoapp:info-index' %}"><button style="background-color:white; border-radius:5px">Назад</button></a>
</div>
{% endblock  %}

mysite/arduinoapp/templates/arduinoapp/info-create.html
{% extends "arduinoapp/base.html" %}


{% block title %}
    Create Station
{% endblock  %}

{% block body %}
    <h1>Добавление данных для станции</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
             {% csrf_token %}
             {{form.as_p}}

        <button type="submit" style="background-color:white; border-radius:5px">
            Создание
        </button>
    </form>
    </div>
  
    <div>
        <a href="{% url 'arduinoapp:info-index' %}"><button style="background-color:white; border-radius:5px">Возвращение на главную страницу</button></a>
    </div>
{% endblock  %}

mysite/arduinoapp/templates/arduinoapp/info-index.html
{% extends "arduinoapp/base.html" %}

{% block title %}
Главная страница РЦС-4
{% endblock %}

{% block body %}
<!--<meta http-equiv="Refresh" content="15" />-->


<h1>Главная страница приложения РЦС-4</h1>
<div>
    <ul>
        {% for name, temperature_info in stations %}
        <li>{{name|linenumbers}} ({{name|length}}) {{temperature_info}}</li>
    </ul>
    {% endfor %}


<div>
    <a href="{% url 'arduinoapp:info-Saratov_1RCS4' %}"><button style="background-color:white; border-radius:5px">Саратов-1ard</button></a>
</div>
<div>
    <a href="{% url 'arduinoapp:rcs-index' %}"><button style="background-color:white; border-radius:5px">Назад</button></a>
</div>

{% endblock %}

mysite/arduinoapp/templates/arduinoapp/info-list.html
{% extends "arduinoapp/base.html" %}

{% block title %}
    Info list
{% endblock  %}

{% block body %}
<h1>Перечень станций </h1>
{% if stations.all %}
<div>
    {% for station in stations.all%}
    <div>
        <p>Станция: {{station.name}}</p>
        <p>Информация о станции: {{station.temperature_info}}</p>
        <p> Информация когда была загружена: {{station.data_created}}</p>
        {% endfor %}
</div>
    {% else %}
    <h3>Станции не загруженны</h3>
    {% endif %}
</div>
<a href="{% url 'arduinoapp:info-create' %}"><button style="background-color:white; border-radius:5px">Создание новой станции</button></a>
<a href="{% url 'arduinoapp:arduino-create' %}"><button style="background-color:white; border-radius:5px">Создание нового ардуино</button></a>
{% endblock  %}

mysite/arduinoapp/templates/arduinoapp/info-settings.html
{% extends "arduinoapp/base.html" %}

{% block title %}
Управление оборудованием
{% endblock %}

{% block body %}
<h1>Управление оборудованием</h1>
<div>
    <a href="{% url 'arduinoapp:info-arduino' %}"><button style="background-color:white; border-radius:5px" >Управление Ардуино</button></a>
</div>
{% endblock%}

mysite/arduinoapp/templates/arduinoapp/rcs-index.html
{% extends "arduinoapp/base.html" %}

{% block title %}
Структурныйе подразделения Дирекции связи
{% endblock %}
{% block body %}
<h1>Структурные подразделения Дирекции связи</h1>

<div style="position: absolute; top: 10px; right: 10px;">
    Добро пожаловать, {{ user.username }}
</div>
<div>
    <a href="{% url 'rcs_1:info-index' %}"><button style="background-color:white; border-radius:5px">РЦС-1</button></a>
</div>
<div>
    <a href="{% url 'rcs_2:info-index' %}"><button style="background-color:white; border-radius:5px">РЦС-2</button></a>
</div>
<div>
    <a href="{% url 'arduinoapp:info-index' %}"><button style="background-color:white; border-radius:5px">РЦС-4</button></a>
</div>
<div>
      <a href="{% url 'myauth:register' %}"><button style="background-color:white; border-radius:5px" >Регистрация</button></a>
</div>
<div>
      <a href="{% url 'myauth:login' %}"><button style="background-color:white; border-radius:5px" >Войти</button></a>
</div>
<div>
      <a href="{% url 'myauth:logout' %}"><button style="background-color:white; border-radius:5px" >Выйти</button></a>
</div>

<img src="/static/img/Безымянный.jpg" alt="logo" style="position: relative; ">

{%  endblock %}