mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', include('arduinoapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('rcs_1/', include("rcs_1.urls")),
    path('rcs_2/', include("rcs_2.urls")),
    path("req/", include("requestdataapp.urls")),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path("api/", include("myapiapp.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/rcs_1/urls.py
from django.urls import include
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import InfoIndexView, StationListView, ArduinoCreateView, ArduinoListView, usb_web, StationCreateView, MicrocomputerListView, MicrocomputerCreateView
app_name = 'rcs_1'

routers = DefaultRouter()

urlpatterns = [
    path('', InfoIndexView.as_view(), name='info-index'),
    path("station/", StationListView.as_view(), name="info-list"),
    path("station/create/", StationCreateView.as_view(), name="info-create"),
    path("arduino/create/", ArduinoCreateView.as_view(), name="arduino-create"),
    path("arduino/list/", ArduinoListView.as_view(), name="arduino-list"),
    path("arduino/info/", usb_web, name="info-arduino"),
    path("micro/create/", MicrocomputerCreateView.as_view(), name="micro-create"),
    path("micro/list/", MicrocomputerListView.as_view(), name="micro-list"),
]

mysite/rcs_2/urls.py
from django.urls import include
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import InfoIndexView, StationListView, ArduinoCreateView, ArduinoListView, usb_web, StationCreateView, MicrocomputerListView, MicrocomputerCreateView
app_name = 'rcs_2'

routers = DefaultRouter()

urlpatterns = [
    path('', InfoIndexView.as_view(), name='info-index'),
    path("station/", StationListView.as_view(), name="info-list"),
    path("station/create/", StationCreateView.as_view(), name="info-create"),
    path("arduino/create/", ArduinoCreateView.as_view(), name="arduino-create"),
    path("arduino/list/", ArduinoListView.as_view(), name="arduino-list"),
    path("arduino/info/", usb_web, name="info-arduino"),
    path("micro/create/", MicrocomputerCreateView.as_view(), name="micro-create"),
    path("micro/list/", MicrocomputerListView.as_view(), name="micro-list"),
]

mysite/rcs_2/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


def product_document_directory_path(instance: "Station", filename: str) -> str:
    return "station/station_{pk}/documents/{filename}".format(
        pk=instance,
        filename=filename,
    )

class Station(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100) # Station name
    temperature_info = models.CharField(max_length=100) # Station temperature info
    data_created = models.DateTimeField(default=timezone.now)
    documents = models.FileField(null=True, blank=True, upload_to=product_document_directory_path)

    def __str__(self):
        return self.name # Station name

    class Meta:
        verbose_name = 'Stations' # Station name
class Arduino(models.Model):
    """
    Модель Arduino предоставляет информацию о состоянии
    темперартуры на станции
    """
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    temperature_info = models.IntegerField(default=0)
    update_data = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Arduino' # Arduino name

class Microcomputer(models.Model):
    """
    Модель Microcomputer предоставляет информацию о состоянии
    темперартуры на станции
    """
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    temperature_info = models.IntegerField(default=0)
    update_data = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Microcomputer'  # Microcomputer name


class Sensor_Data(models.Model):
    """"
    Модель Sensor_Data предоставляет
    информацию о температуре на станции
    """
    name = models.CharField(max_length=200)
    temperature_info = models.IntegerField(default=0)

mysite/rcs_2/forms.py
from django import forms
from .models import Station, Arduino, Microcomputer

class StationForm(forms.ModelForm):
    class Meta:
        model = Station
        fields = 'name', "temperature_info"


class ArduinoForm(forms.ModelForm):
    class Meta:
        model = Arduino
        fields = 'name', "temperature_info", "station"


class MicrocomputerForm(forms.ModelForm):
    class Meta:
        model = Microcomputer
        fields = 'name', "temperature_info", "station"

mysite/rcs_2/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView
from .forms import StationForm
from .models import Station, Arduino, Sensor_Data, Microcomputer


# Create your views here.


class InfoIndexView(View):
    """
    Главная страница сайта
    """
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(request, 'rcs_2/info-index.html')

class StationListView(ListView):
    """
    Список станций и какая-то информация о ней
    """
    template_name = 'rcs_2/info-list.html'
    context_object_name ='station'
    queryset = Station.objects.all()

    def station_create(self, request: HttpRequest) -> HttpResponse:
        """
        Создание станции
        :param request:
        :return:
        """
        if request.method == 'POST':
            form = StationForm(request.POST)
            if form.is_valid():
                form.save()
                url = reverse("rcs_2/info-list.html")
                return redirect(url)
        else:
            form = StationForm()
        context = {
            'form': form
        }
        return render(request, 'rcs_2/info-create.html', context=context)

class StationCreateView(CreateView):
    """
    Создание станции и какая-то информация о ней
    """
    model = Station
    fields = "name", "temperature_info", "documents",
    template_name = 'rcs_2/info-create.html'
    success_url = reverse_lazy("rcs_2:info-create")


class ArduinoCreateView(CreateView):
    """
    Создание Arduino и какая-то информация о ней
    """
    model = Arduino
    fields = "name", "temperature_info", "station"
    template_name = 'rcs_2/arduino-create.html'
    success_url = reverse_lazy("rcs_2:arduino-create")


class MicrocomputerCreateView(CreateView):
    """
    Создание микрокомпьютера и какая-то информация о ней
    """
    model = Microcomputer
    fields = "name", "temperature_info", "station"
    template_name = 'rcs_2/micro-create.html'
    success_url = reverse_lazy("rcs_2:micro-create")

class MicrocomputerListView(ListView):
    """
    Список микрокомпьютеров
    """
    template_name = "rcs_2/micro-list.html"
    context_object_name = "microcomputers"
    queryset = Microcomputer.objects.all()


class ArduinoListView(ListView):
    """
    Список Arduino
    """
    template_name = "rcs_2/arduino-list.html"
    context_object_name = "arduinos"
    queryset = Arduino.objects.all()


def usb_web(request: HttpRequest) -> HttpResponse:
    """
    Информация с Arduino
    """
    with open("arduino.csv", "r", encoding="utf-8") as file:
        for line in file.read().split("\n"):  # Про тестить maxsplit, что бы произвести разделение на несколько строк
            name = line.strip().split(",")
            Sensor_Data.objects.create(name=name)
            data_sensor = [
                ("", line)
            ]
            context = {
                "data_sensor": data_sensor,
            }
            return render(request, "rcs_2/info-arduino.html", context=context)


class DataSensorListView(ListView):
    """
    Информаця с Arduino для анализа
    и работы с этими данными
    """
    template_name = "rcs_2/info-arduino.html"
    context_object_name = "Sensor_datas"
    queryset = Sensor_Data.objects.all()

mysite/rcs_2/templates/rcs_2/arduino-create.html
{% extends "rcs_2/base.html" %}

{% block title %}
    Create Arduino
{% endblock  %}

{% block body %}
    <h1>Добавление даных с ардуино</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" style="background-color:white; border-radius:5px">
                Создание
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'rcs_2:info-list' %}"><button style="background-color:white; border-radius:5px">Возвращение на страницу с перечнем станций и ардуино</button></a>
    </div>
    <div>
        <a href="{% url 'rcs_2:info-index' %}"><button style="background-color:white; border-radius:5px">Возвращение на главную страницу</button></a>
    </div>
{% endblock  %}

mysite/rcs_2/templates/rcs_2/arduino-list.html
{% extends "rcs_2/base.html" %}

{% block title %}
    Info list
{% endblock  %}

{% block body %}
<div>
    {% if arduinos.all %}
    {% for arduino in arduinos.all %}
        <p> Имя микроконтроллера: {{arduino.name}}</p>
        <p> Информация с датчика температуры: {{arduino.temperature_info}}</p>
        <p> На какой станции он находится микроконтроллер: {{arduino.station}}
        <p> Информация когда была загружена: {{arduino.update_data}}</p>
        {% endfor %}
    </div>
    {% else %}
    <h3>Станции не загруженны</h3>
    {% endif %}
    <div>
        <a href="{% url 'rcs_2:info-create' %}"><button style="background-color:white; border-radius:5px">Создать новую станцию</button></a>
    </div>
    <div>
        <a href="{% url 'rcs_2:arduino-create' %}"><button style="background-color:white; border-radius:5px">Создать новый ардуино</button></a>
    </div>
    <div>
        <a href="{% url 'rcs_2:info-index' %}"><button style="background-color:white; border-radius:5px">Возвращение на главную страницу</button></a>
    </div>
{% endblock  %}

mysite/rcs_2/templates/rcs_2/base.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
    <style>
        body {
            background-color: gray;
        }
    </style>
</head>
<body>
{% block body %}
Base Body
{% endblock %}

<div>
    Время: {% now 'H:i'%}
</div>
<div>
    {% now 'l' as current_weekday%}
    Сегодня: {{current_weekday}}
</div>
</body>
</html>

mysite/rcs_2/templates/rcs_2/info-create.html
{% extends "rcs_2/base.html" %}


{% block title %}
    Создание Станции
{% endblock  %}

{% block body %}
    <h1>Добавление данных для станции</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
             {% csrf_token %}
             {{form.as_p}}

        <button type="submit" style="background-color:white; border-radius:5px">
            Создание
        </button>
    </form>
    </div>

    <div>
        <a href="{% url 'rcs_2:info-index' %}"><button style="background-color:white; border-radius:5px">Возвращение на главную страницу</button></a>
    </div>
{% endblock  %}

mysite/rcs_2/templates/rcs_2/info-index.html
{% extends "rcs_2/base.html" %}

{% block title %}
Главная страница РЦС-2
{% endblock %}

{% block body %}
<h1>Главная страница РЦС-2</h1>

<div>
    <ul>
        {% for name, temperature_info in stations %}
        <li>{{name|linenumbers}} ({{name|length}}) {{temperature_info}}</li>
    </ul>
    {% endfor %}
<div>
    Time running: {{ time_running }}
</div>

<div>
    <a href="{% url 'rcs_2:info-create' %}"><button style="background-color:white; border-radius:5px">Здесь ты можешь добавить станцию</button></a>
</div>
<div>
    <a href="{% url 'rcs_2:info-list' %}"><button style="background-color:white; border-radius:5px" >Список станций</button></a>
</div>
<div>
    <a href="{% url 'rcs_2:arduino-list' %}"><button style="background-color:white; border-radius:5px" >Список Arduino</button></a>
</div>
<div>
    <a href="{% url 'rcs_2:info-arduino' %}"><button style="background-color:white; border-radius:5px" >Данные с Ардуино</button></a>
</div>
<div>
    <a href="{% url 'rcs_2:arduino-create' %}"><button style="background-color:white; border-radius:5px" >Здесь ты можешь добавить Arduino</button></a>
</div>
<div>
    <a href="{% url 'rcs_2:micro-create' %}"><button style="background-color:white; border-radius:5px" >Здесь ты можешь добавить Микрокомпьютер</button></a>
</div>
<div>
    <a href="{% url 'rcs_2:micro-list' %}"><button style="background-color:white; border-radius:5px" >Список Микрокомпьютеров</button></a>
</div>


{% endblock %}

mysite/rcs_2/templates/rcs_2/info-list.html
{% extends "rcs_2/base.html" %}

{% block title %}
Информация об РЦС-2
{% endblock  %}

{% block body %}
<h1>Информация об РЦС-2</h1>
<div>
    {% if stations.all %}
    {% for station in stations.all %}
        <p>Станция: {{station.name}}</p>
        <p>Информация о станции: {{station.temperature_info}}</p>
        {% endfor %}
    </div>
    {% else %}
    <h3>Станции не загруженны</h3>
    {% endif %}

<a href="{% url 'rcs_2:info-create' %}"><button style="background-color:white; border-radius:5px">Создание новой станции</button></a>
<a href="{% url 'rcs_2:arduino-create' %}"><button style="background-color:white; border-radius:5px">Создание нового ардуино</button></a>
{% endblock  %}

mysite/rcs_2/templates/rcs_2/micro-create.html
{% extends "rcs_2/base.html" %}

{% block title %}
    Create Microcomputer
{% endblock  %}

{% block body %}
    <h1>Добавление данных с микрокомпьютера</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" style="background-color:white; border-radius:5px">
                Создание
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'rcs_2:info-list' %}"><button style="background-color:white; border-radius:5px">Возвращение на страницу с перечнем станций и ардуино</button></a>
    </div>
    <div>
        <a href="{% url 'rcs_2:info-index' %}"><button style="background-color:white; border-radius:5px">Возвращение на главную страницу</button></a>
    </div>
{% endblock  %}

mysite/rcs_2/templates/rcs_2/micro-list.html
{% extends "rcs_2/base.html" %}

{% block title %}
    Info list
{% endblock  %}

{% block body %}
<div>
    {% if Microcomputers.all %}
    {% for arduino in Microcomputers.all %}
        <p> Имя микроконтроллера: {{Microcomputer.name}}</p>
        <p> Информация с датчика температуры: {{Microcomputer.temperature_info}}</p>
        <p> На какой станции он находится микроконтроллер: {{Microcomputer.station}}
        <p> Информация когда была загружена: {{Microcomputer.update_data}}</p>
        {% endfor %}
    </div>
    {% else %}
    <h3>Станции не загруженны</h3>
    {% endif %}
    <div>
        <a href="{% url 'rcs_2:info-create' %}"><button style="background-color:white; border-radius:5px">Создать новую станцию</button></a>
    </div>
    <div>
        <a href="{% url 'rcs_2:micro-create' %}"><button style="background-color:white; border-radius:5px">Создать новый микрокомпьютер</button></a>
    </div>
    <div>
        <a href="{% url 'rcs_2:info-index' %}"><button style="background-color:white; border-radius:5px">Возвращение на главную страницу</button></a>
    </div>
{% endblock  %}